services:
  laravel:
    container_name: laravel
    build:
      context: ./
      dockerfile: laravel.dockerfile
    image: laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - lv_network
    
  vue:
    container_name: vue
    build:
      context: ../frontend_vue_laravel_bot
      dockerfile: vue.dockerfile
    volumes:
      - ../frontend_vue_laravel_bot:/app:cached
    expose:
      - "80"
    restart: always
    ports:
      - "3000:3000"
    networks:
      - lv_network

  database:
    container_name: database
    image: mysql
    volumes:
      - ../mysql_data:/var/lib/mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bd_ventas
      MYSQL_USER: root1
      MYSQL_PASSWORD: root1   
    networks:
      - lv_network   

  webserver:
    container_name: webserver
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    depends_on:
      - laravel
      - vue
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - lv_network

networks:
  lv_network:

volumes:
  mysql_data:
